component_depth: 2
languages:
- php
- javascript
exclude:
- /vendor/.*
- /web/.*
- /data/.*
- /app/.*
- /bin/.*
- /componentes/.*
- /src/TransactionsBundle/Resources/public/js/highcharts.js
- /src/TransactionsBundle/Resources/public/js/tableSorter.js
