language: php

php:
  - 7.0
  - 7.1
  - 5.5

before_script:
  - composer install --dev
  - npm i -g phplint
  - php app/console assetic:dump
  - phplint '**/*.php' '!vendor/**' '!app/cache/**'

script: phpunit -c app/phpunit.xml.dist
