categories:
    resource: "@CategoriesBundle/Controller/"
    type:     annotation
    prefix:   /

budget:
    resource: "@BudgetBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    resource: "@LoginBundle/Controller/"
    type:     annotation
    prefix:   /

account:
    resource: "@TransactionsBundle/Controller/"
    type:     annotation
    prefix:   /
