# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    filter_listener:
        class: TransactionsBundle\EventListener\FilterListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"
        tags:
            -
                name: kernel.event_listener
                event: kernel.request
                method: onKernelRequest
    transactions.match:
        class: TransactionsBundle\Service\MatchService
        arguments:
            - @account.account_repository
            - @account.category_repository
            - @doctrine.orm.entity_manager
            - @event_dispatcher
    account.account_service:
        class: AccountBUndle\Service\AccountService
        arguments:
            - @account.account_repository
            - @event_dispatcher
    account.account_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments: [ TransactionsBundle\Entity\Transactions]
    account.category_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments: [ CategoriesBundle\Entity\Categories]
    account.menu:
        class: TransactionsBundle\Service\MenuService
