services:
  account.account_service:
      class: AccountBundle\Service\AccountService
      arguments:
          - @account.account_repository
          - @event_dispatcher
  account.account_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine", getRepository]
    arguments: [ AccountBundle\Entity\Transactions]
#    account.example:
#        class: AccountBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
